### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by ToracX** [ksecord/dreamscreen-node#8]
Thanks for making this code.
The interactive-cli is working like a charm, quick and easy.

Sadly the example code does not work for me:

`var DreamScreenClient = require('../lib/dreamscreen').Client;
var client = new DreamScreenClient();

client.on('light-new', function (light) {
   light.setMode(3, function (err) {
      if (!err) {
         console.log(`${light.name} set Mode 3 success`);
      }
   });
});` 

It does not throw up any errors it straight up does not change my dream screen. 

Might this be because there is no `client.init();`

`var DreamScreenClient = require('../lib/dreamscreen').Client;
var client = new DreamScreenClient();

client.init();

client.on('light-new', function (light) {
   light.setMode(0)
});

client.destroy();`

For me the above code works.
Do you have any clue?

**Comment by ksecord** [comment]
whoops yeah interactive-cli is correct, readme is wrong (just never changed it). sorry about that
